name: v9-c

anchor:
  reg_max: 16
  strides: [8, 16, 32]

early_exit:
#   dynamic: entropy
  dynamic: confidence
  confidence: 0.5
  specified_layer: 1

model:
  backbone:
    - Conv:
        args: {out_channels: 64, kernel_size: 3, stride: 2}
        source: 0
        tags: C1

    - Conv:
        args: {out_channels: 128, kernel_size: 3, stride: 2}
        source: C1
        tags: C2

    - EarlyExitSampler:
        args: {in_channels: 128, out_channels: 256, output_size: 80}
    - EarlyExitSampler:
        args: {in_channels: 128, out_channels: 512, output_size: 40}
        source: -2
    - EarlyExitSampler:
        args: {in_channels: 128, out_channels: 1024, output_size: 20}
        source: -3
    - EarlyExitMultiheadDetection:
        output: True
        source: [-3, -2, -1]

    - RepNCSPELAN:
        args: {out_channels: 256, part_channels: 128}
        source: C2
        tags: C3

    - ADown:
        args: {out_channels: 256}
        source: C3
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 256}
        tags: B3

    - EarlyExitSampler:
        args: {in_channels: 512, out_channels: 256, output_size: 80}
    - EarlyExitSampler:
        args: {in_channels: 512, out_channels: 512, output_size: 40}
        source: -2
    - EarlyExitSampler:
        args: {in_channels: 512, out_channels: 1024, output_size: 20}
        source: -3
    - EarlyExitMultiheadDetection:
        output: True
        source: [-3, -2, -1]

    - ADown:
        args: {out_channels: 512}
        source: B3
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: B4

    - ADown:
        args: {out_channels: 512}
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: B5

    - EarlyExitSampler:
        args: {in_channels: 512, out_channels: 256, output_size: 80}
    - EarlyExitSampler:
        args: {in_channels: 512, out_channels: 512, output_size: 40}
        source: -2
    - EarlyExitSampler:
        args: {in_channels: 512, out_channels: 1024, output_size: 20}
        source: -3
    - EarlyExitMultiheadDetection:
        output: True
        source: [-3, -2, -1]

  neck:
    - SPPELAN:
        args: {out_channels: 512}
        source: B5
        tags: N3

    

    - UpSample:
        args: {scale_factor: 2, mode: nearest}
        tags: U1
    - Concat:
        source: [U1, B4]
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: N4

    - UpSample:
        args: {scale_factor: 2, mode: nearest}
    - Concat:
        source: [-1, B3]
        tags: C4

    - EarlyExitSampler:
        args: {in_channels: 1024, out_channels: 256, output_size: 80}
    - EarlyExitSampler:
        args: {in_channels: 1024, out_channels: 512, output_size: 40}
        source: -2
    - EarlyExitSampler:
        args: {in_channels: 1024, out_channels: 1024, output_size: 20}
        source: -3
    - EarlyExitMultiheadDetection:
        output: True
        source: [-3, -2, -1]

  head:
    - RepNCSPELAN:
        args: {out_channels: 256, part_channels: 256}
        tags: P3
        source: C4

    - ADown:
        args: {out_channels: 256}
    - Concat:
        source: [-1, N4]
        tags: C5

    - EarlyExitSampler:
        args: {in_channels: 768, out_channels: 256, output_size: 80}
    - EarlyExitSampler:
        args: {in_channels: 768, out_channels: 512, output_size: 40}
        source: -2
    - EarlyExitSampler:
        args: {in_channels: 768, out_channels: 1024, output_size: 20}
        source: -3
    - EarlyExitMultiheadDetection:
        output: True
        source: [-3, -2, -1]

    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: P4
        source: C5

    - ADown:
        args: {out_channels: 512}
    - Concat:
        source: [-1, N3]
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: P5

  detection:
    - MultiheadDetection:
        source: [P3, P4, P5]
        tags: Main
        output: True

  auxiliary:
    - CBLinear:
        source: B3
        args: {out_channels: [256]}
        tags: R3
    - CBLinear:
        source: B4
        args: {out_channels: [256, 512]}
        tags: R4
    - CBLinear:
        source: B5
        args: {out_channels: [256, 512, 512]}
        tags: R5

    - Conv:
        args: {out_channels: 64, kernel_size: 3, stride: 2}
        source: 0
    - Conv:
        args: {out_channels: 128, kernel_size: 3, stride: 2}
    - RepNCSPELAN:
        args: {out_channels: 256, part_channels: 128}

    - ADown:
        args: {out_channels: 256}
    - CBFuse:
        source: [R3, R4, R5, -1]
        args: {index: [0, 0, 0]}
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 256}
        tags: A3

    - ADown:
        args: {out_channels: 512}
    - CBFuse:
        source: [R4, R5, -1]
        args: {index: [1, 1]}
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: A4

    - ADown:
        args: {out_channels: 512}
    - CBFuse:
        source: [R5, -1]
        args: {index: [2]}
    - RepNCSPELAN:
        args: {out_channels: 512, part_channels: 512}
        tags: A5

    - MultiheadDetection:
        source: [A3, A4, A5]
        tags: AUX
        output: True
